[package]
name = "todos-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
todos-adapter = { path = "../todos-adapter" }
todos-infra = { path = "../todos-infra" }
